---
version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "monthly"
    rebase-strategy: "disabled"
    labels:
      - "no-API"
    commit-message:
      prefix: "go-ceph"
