---
version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"
    labels:
      - rebase
    commit-message:
      prefix: "rebase"
